### ISSUE TITLE
Feature Request: Customize when days begin

### ISSUE THREAD

**Issue by LilSpurrell** [open-nomie/nomie5#168]
My "day" ends around 3am, but anything I log between 12 and 3 ends up affecting averages of that tracker for the following day. Technically this would be correct, but I would really like for those logs to go into my averages/sums for the day I choose. Aka I would like to be able to specify that the day changes over at 3am rather than 12am.

**Comment by brandoncorbin** [comment]
This feature has been requested at least 1 time a year - however, the requirements for pulling this off is massive and would require us to touch every single place a date is used - which is everywhere.  Sadly I have yet to even come close to a solution, so I don't think this will be happening.
